import io
from datetime import datetime, timezone
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable


def generate_pdf_report(result: dict, filename: str, media_type: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            topMargin=2*cm, bottomMargin=2*cm,
                            leftMargin=2*cm, rightMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle("KyrosTitle", parent=styles["Title"],
                                 alignment=TA_CENTER, fontSize=22, spaceAfter=6)
    story.append(Paragraph("KYROS Deepfake Analysis Report", title_style))
    story.append(Paragraph(
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        styles["Normal"],
    ))
    story.append(HRFlowable(width="100%", color=colors.grey, spaceAfter=12))

    is_fake = result.get("isDeepfake", False)
    verdict_text = "DEEPFAKE DETECTED" if is_fake else "CONTENT AUTHENTIC"
    verdict_style = ParagraphStyle("Verdict", parent=styles["Heading1"],
                                   textColor=colors.red if is_fake else colors.green,
                                   fontSize=18, spaceAfter=4)
    story.append(Paragraph(verdict_text, verdict_style))
    story.append(Paragraph(
        f"Confidence: <b>{result.get('confidence', 0)}%</b>  |  "
        f"Processing time: <b>{result.get('processingTime', 'N/A')}s</b>",
        styles["Normal"],
    ))
    story.append(Spacer(1, 12))

    story.append(Paragraph("File Information", styles["Heading2"]))
    file_data = [
        ["Filename", filename],
        ["Media Type", media_type],
        ["Analysis Date", datetime.now(timezone.utc).strftime("%Y-%m-%d")],
    ]
    t = Table(file_data, colWidths=[5*cm, 11*cm])
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("BACKGROUND", (0, 0), (0, -1), colors.Color(0.9, 0.9, 0.95)),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.Color(0.97, 0.97, 1.0)]),
    ]))
    story.append(t)
    story.append(Spacer(1, 16))

    if result.get("details"):
        story.append(Paragraph("Analysis Details", styles["Heading2"]))
        detail_data = [["Parameter", "Value"]] + [[d["label"], d["value"]] for d in result["details"]]
        dt = Table(detail_data, colWidths=[6*cm, 10*cm])
        dt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.2, 0.3, 0.5)),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.Color(0.97, 0.97, 1.0)]),
        ]))
        story.append(dt)
        story.append(Spacer(1, 16))

    story.append(HRFlowable(width="100%", color=colors.grey, spaceAfter=8))
    story.append(Paragraph(
        "<i>This report was generated by KYROS Authenticity Verification System. "
        "Results are for guidance only and should be verified by a qualified professional "
        "before being used in legal or critical contexts.</i>",
        styles["Normal"],
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()
